mkdir_if_not_exists \
    "$XDG_CACHE_HOME/build/c" \
    "$XDG_CACHE_HOME/build/cpp" \
    "$XDG_CACHE_HOME/build/objc" \
    "$XDG_CACHE_HOME/build/swift" \
    "$XDG_CACHE_HOME/tags" \
    "$XDG_CACHE_HOME/vim/backup" \
    "$XDG_CACHE_HOME/vim/swp" \
    "$XDG_CACHE_HOME/vim/undo" \
